I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 70, in script
    python:
  File "game/script.rpy", line 71, in <module>
    readLine("prologue1.txt")
  File "game/script.rpy", line 25, in readLine
    print(readLines(line.strip()))
  File "game/script.rpy", line 30, in readLines
    changeStats(oneLine[2])
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 70, in script
    python:
  File "C:\Users\1o8zh\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\1o8zh\Downloads\renpy-8.3.7-sdk\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 71, in <module>
    readLine("prologue1.txt")
  File "game/script.rpy", line 25, in readLine
    print(readLines(line.strip()))
  File "game/script.rpy", line 30, in readLines
    changeStats(oneLine[2])
IndexError: list index out of range

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Funny Project 1.0
Wed Jul 16 17:26:40 2025
