I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 63, in script
    define person = Character([player_name])
  File "game/script.rpy", line 63, in <module>
    define person = Character([player_name])
NameError: name 'player_name' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 63, in script
    define person = Character([player_name])
  File "C:\Users\1o8zh\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 2248, in execute
    self.set()
  File "C:\Users\1o8zh\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 2262, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\1o8zh\Downloads\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 63, in <module>
    define person = Character([player_name])
NameError: name 'player_name' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Funny Project 1.0
Mon Jul  7 22:30:51 2025
